debug = false
random_seed = 0xc61dd8fc

[data]
num_features = 1
num_samples = 50
sigma_noise = 0.5

[training]
batch_size = 16
num_iters = 300
learning_rate = 0.1

[plotting]
output_dir = "artifacts"
figsize = [5, 3]
dpi = 200
