debug = false
random_seed = 0xc61dd8fc

[data]
num_features = 2
num_samples = 1000
sigma_noise = 0.1

[training]
batch_size = 32
num_iters = 300
learning_rate = 0.1
num_layers = 5
hidden_layer_width = 10
log_clip = 1e-8

[plotting]
output_dir = "artifacts"
figsize = [5, 5]
dpi = 200
linspace = 200
